name: Build and Push Docker image

on:
  push:
    branches:
      - master    # ← 今 master でやってるなら master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/atomcatserver:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/atomcatserver:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22  # 必要なら変更
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/atomcatserver:latest
          docker stop tomcat-container || true
          docker rm tomcat-container || true
          docker run -d --name tomcat-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/atomcatserver:latest
